modLoader       = "javafml"
loaderVersion   = "[37,38)"
license         = "MIT License"
issueTrackerURL = "https://github.com/srscode/FallThru/issues/"

[[mods]]
modId           = "fallthru"
version         = "${file.jarVersion}"
displayName     = "FallThru"
#updateJSONURL  = ""
displayURL      = "https://srscode.github.io/FallThru/"
logoFile        = "fallthru-banner.png"
credits         = "https://github.com/srscode/FallThru/graphs/contributors"
authors         = "srs-bsns"
description     = '''
FallThru allows the modifying of solid blocks, such as leaves, so that entities can pass through them, or for applying speed reductions to blocks that are already non-solid, such as tall grass.

The configuration is versatile and each block can be configured individually.
'''

[[dependencies.fallthru]]
modId           = "forge"
mandatory       = true
versionRange    = "[37.0.59,38)" # 37.0.59 is the minimum version for Mixin, 38.x contains breaking refactors
ordering        = "NONE"
side            = "BOTH"

[[dependencies.fallthru]]
modId           = "minecraft"
mandatory       = true
versionRange    = "[1.17.1,1.18)"
ordering        = "NONE"
side            = "BOTH"
