modLoader       = "javafml"
loaderVersion   = "[28,)"
issueTrackerURL = "https://github.com/srscode/FallThru/issues/"

[[mods]]
modId           = "fallthru"
version         = "${file.jarVersion}"
displayName     = "FallThru"
#updateJSONURL  = ""
displayURL      = "https://srscode.github.io/FallThru/"
logoFile        = "fallthru-banner.png"
credits         = "https://github.com/srscode/FallThru/graphs/contributors"
authors         = "srs-bsns"
description     = '''
FallThru allow the modifying of solid blocks, such as leaves, so that entities can pass through
them, or for applying speed reductions to blocks that are already non-solid, such as tall grass.

The configuration is versatile and each block can be configured individually.
'''

[[dependencies.fallthru]]
modId           = "forge"
mandatory       = true
versionRange    = "[28.1,)"
ordering        = "NONE"
side            = "BOTH"

[[dependencies.fallthru]]
modId           = "minecraft"
mandatory       = true
versionRange    = "[1.14.4,)"
ordering        = "NONE"
side            = "BOTH"
