modLoader       = "javafml"
loaderVersion   = "${loader_version_range}"
license         = "${mod_license}"
issueTrackerURL = "${mod_issue_tracker}"

[[mods]]
modId           = "${mod_id}"
displayName     = "${mod_name}"
version         = "${version}"
description     = '''${mod_description}'''
authors         = "${mod_authors}"
displayURL      = "${mod_url}"
logoFile        = "${mod_logoFile}"

[[dependencies.${mod_id}]]
modId           = "minecraft"
type            = "required"
versionRange    = "${mc_version_range}"
ordering        = "NONE"
side            = "BOTH"


[[dependencies.${mod_id}]]
modId           = "neoforge"
type            = "required"
versionRange    = "${neo_version_range}"
ordering        = "NONE"
side            = "BOTH"

[[mixins]]
config          = "fallthru.mixins.json"
